spring:
  datasource:
    url: ${CATALOG_DB_URL:jdbc:postgresql://localhost:5432/catalogdb}
    username: ${CATALOG_DB_USERNAME:catalog}
    password: ${CATALOG_DB_PASSWORD:catalog}
    driver-class-name: org.postgresql.Driver
  postgres:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
