spring:
  datasource:
    url: ${COMMERCE_DB_URL:jdbc:postgresql://localhost:5432/commercedb}
    username: ${COMMERCE_DB_USERNAME:commerce}
    password: ${COMMERCE_DB_PASSWORD:commerce}
    driver-class-name: org.postgresql.Driver
  postgres:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
